force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Tran-{0000000000}</displayFormat>
        <label>Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_type__c</fullName>
    <label>Transaction type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionRestAPI.cls
@RestResource(urlMapping='/api/Transaction__c/*')
global with sharing class TransactionRestAPI {
    
    @HttpGet
    global static String getDepositTransactions()
    {
        RestRequest request = RestContext.request;
        
        String URI = request.requestURI;
        
        
        
    
        
       //	String type1 = String.valueOf(URI.substring(URI.lastIndexOf('/')+1));
       Map<String,String> tranParams = request.params;
        
        String type1 = tranParams.get('type');
        
        String transactionId = tranParams.get('Id');
        
        List<Transaction__c> transList = [select Amount__c from Transaction__c where Name =: transactionId and Transaction_type__c =:type1];
        Decimal SumofAmount= 0;
        for(Transaction__c tran : transList)
        {
            SumofAmount+=tran.Amount__c;
        }
        
        return 'Total Amount for Desposits is : ' +SumofAmount +'Transaction Type ' +type1;
        
        
    }

}