force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>ACC-{0000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings Account</fullName>
            </value>
            <value>
                <fullName>Current Account</fullName>
            </value>
            <value>
                <fullName>Savings Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/AccountApproved__c.field-meta.xml
<CustomField>
    <fullName>AccountApproved__c</fullName>
    <label>AccountStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Average_Transaction_deposit__c.field-meta.xml
<CustomField>
    <fullName>Average_Transaction_deposit__c</fullName>
    <label>Sum of Transactions (Deposit)</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Transaction_type__c</field>
        <operation>equals</operation>
        <value>Deposit</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Bank_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Average_Transaction_Withdraw__c.field-meta.xml
<CustomField>
    <fullName>Average_Transaction_Withdraw__c</fullName>
    <label>Sum of Transactions (Withdraw)</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Transaction_type__c</field>
        <operation>equals</operation>
        <value>Withdraw</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Bank_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>displays remaining account balance</description>
    <inlineHelpText>account balance</inlineHelpText>
    <label>Balance</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Cities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BHU</fullName>
    </customValue>
    <customValue>
        <fullName>CHAN</fullName>
    </customValue>
    <customValue>
        <fullName>CHN</fullName>
    </customValue>
    <customValue>
        <fullName>HYD</fullName>
    </customValue>
    <customValue>
        <fullName>MUM</fullName>
    </customValue>
    <customValue>
        <fullName>MYS</fullName>
    </customValue>
    <customValue>
        <fullName>PUN</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewCaseListController.cls
public class NewCaseListController {
    public List<Case> getNewCases()
    {
        List<Case>  cases = [select id, CaseNumber,subject,ownerId from Case where status='New'];
        return cases;
        
    }
    
    public List<Account__c> getNewCases1()
    {
        List<Account__c>  Acc = [SELECT Name,AccountApproved__c,Account_Type__c,Average_Transaction_deposit__c,Average_Transaction_Withdraw__c,
                             Balance__c,Bank__c,Branch__c,City__c FROM Account__c ];
        return Acc;
        
    }

}